//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopcoffeebe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public Nullable<bool> gender { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public Nullable<System.DateTime> dwork { get; set; }
        public string pos { get; set; }
        public Nullable<int> branch { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Branch Branch1 { get; set; }
    }
}
